server:
  port: 0
#  address: 127.0.0.1
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int}
#    hostname: localhost
#    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://20.207.203.105:8761/eureka
    healthcheck:
      enabled: true

keycloak:
  realm: scorpius
  auth-server-url: http://20.207.203.105:8180/auth
  ssl-required: none
  resource: frontend
  credentials:
    secret: EarKnJAhU1RdbZLrfICK0n2ZBBK5aOd7
  use-resource-role-mappings: true
  bearer-only: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: frontend
            authorization-grant-type: EarKnJAhU1RdbZLrfICK0n2ZBBK5aOd7
            scope: openid
        provider:
          issuer-uri: http://20.207.203.105:8180/auth/realms/Scorpius
          user-name-attribute: admin
      resourceserver:
        jwt:
          issuer-uri: http://20.207.203.105:8180/auth/realms/Scorpius