server:
  port: 0
#  address: 127.0.0.1
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int}
#    hostname: localhost
#    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://134.209.250.111:8761/eureka
    healthcheck:
      enabled: true

keycloak:
  realm: scorpius
  auth-server-url: http://134.122.71.250:8180/auth
  ssl-required: none
  resource: frontend
  credentials:
    secret: Pk603HpI45mOfrvPXxrQWsQki76Ltpou
  use-resource-role-mappings: true
  bearer-only: true

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 524622551132-cibb53c91n8d4lcm06icgcg5elqlha9p.apps.googleusercontent.com
            clientSecret: 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