spring:
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: rabbitmq-user
    password: '{cipher}3adfb46bde0f96695af1853733d8774f0012b158e34b64a1254660f509c65e1b666020c71b435e7a78a36d31c2845cbf'
  datasource:
    url: jdbc:mysql://34.170.110.240/chat_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: $Tnh210302
  jpa:
    hibernate:
      ddl-auto: validate
  forward-headers-strategy: framework
logging:
  level:
    pl:
      kubaretip:
        chatservice: debug

keycloak:
  realm: scorpius
  auth-server-url: http://keycloak/auth
  ssl-required: external
  resource: frontend
  credentials:
    secret: m7DOTQGjJmigOY6s9AeNHUzJ5xLSxNp5
  use-resource-role-mappings: true
  bearer-only: true
