spring:
  datasource:
    url: jdbc:mysql://34.170.110.240/auth_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: $Tnh210302
  jpa:
    hibernate:
      ddl-auto: validate
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: fasle
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: rabbitmq-user
    password: '{cipher}00c143e772cb49e03cef267ec4da54871c921726ab7a7b07b556048c36547d22a4444b36b4af4e66a07bb563eda5d44c'
logging:
  level:
    com:
      scorpius:
        authservice: debug

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

#server:
#  forward-headers-strategy: framework

keycloak:
  realm: scorpius
  auth-server-url: http://34.125.87.47:8180/auth
  ssl-required: none
  resource: frontend
  credentials:
    secret: as9y1ZpSA57eQMDJmHTtvfIFAaWhPmlY
  use-resource-role-mappings: true
  bearer-only: true
