spring:
  datasource:
    url: jdbc:mysql://localhost:3366/auth_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq-user
    password: '{cipher}3adfb46bde0f96695af1853733d8774f0012b158e34b64a1254660f509c65e1b666020c71b435e7a78a36d31c2845cbf'
logging:
  level:
    com:
      tnh:
        authservice: debug

server:
  port: 9999
  forward-headers-strategy: framework

keycloak:
  realm: scorpius
  auth-server-url: http://keycloak:8180/auth
  ssl-required: external
  resource: frontend
  credentials:
    secret: m7DOTQGjJmigOY6s9AeNHUzJ5xLSxNp5
  use-resource-role-mappings: true
  bearer-only: true