spring:
  datasource:
    url: jdbc:mysql://34.170.110.240/auth_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: $Tnh210302
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq-user
    password: '{cipher}'
logging:
  level:
    com:
      tnh:
        authservice: debug

server:
  port: 9999
  forward-headers-strategy: framework

keycloak:
  realm: scorpius
  auth-server-url: http://keycloak:8180/auth
  ssl-required: external
  resource: frontend
  credentials:
    secret: m7DOTQGjJmigOY6s9AeNHUzJ5xLSxNp5
  use-resource-role-mappings: true
  bearer-only: true