spring:
  datasource:
    url: jdbc:sqlserver://hn.database.windows.net:1433;database=authdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: 'hazy@hn'
    password: '@h0917815161'
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq-user
    password: '{cipher}3adfb46bde0f96695af1853733d8774f0012b158e34b64a1254660f509c65e1b666020c71b435e7a78a36d31c2845cbf'
  redis:
    host: 35.219.5.96
    port: 6379

logging:
  level:
    com:
      tnh:
        authservice: debug

server:
  address: 125.235.232.185

keycloak:
  realm: scorpius
  auth-server-url: http://keycloak:8180/auth
  ssl-required: external
  resource: frontend
  credentials:
    secret: lkxSDijfDceqoNEZ4b2k1HKFB8snWHf9
  use-resource-role-mappings: true
  bearer-only: true